repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black

  - repo: https://github.com/PyCQA/docformatter
    rev: "v1.6.5"
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        args: [ -i ]
        language: python
        types: [ python ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.264"
    hooks:
      - id: ruff
        name: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
