name: Assess code format

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Code quality checks
        run: |
          isort --check-only .
          black --check .
          ruff check .

      - name: Test with pytest
        run: |
          pytest tests/
